package runtheworld.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import runtheworld.entity.DanmuZan;
import runtheworld.entity.DanmuZanExample;

public interface DanmuZanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu_zan
     *
     * @mbggenerated Tue May 22 12:44:23 GMT+08:00 2018
     */
    int countByExample(DanmuZanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu_zan
     *
     * @mbggenerated Tue May 22 12:44:23 GMT+08:00 2018
     */
    int deleteByExample(DanmuZanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu_zan
     *
     * @mbggenerated Tue May 22 12:44:23 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * 根据id进行逻辑删除弹幕
     * @param modifiedTime
     * @return
     */
    int deleteByUk(@Param("danmuId") Long danmuId,@Param("userId") Long userId,@Param("modifiedTime") Date modifiedTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu_zan
     *
     * @mbggenerated Tue May 22 12:44:23 GMT+08:00 2018
     */
    int insert(DanmuZan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu_zan
     *
     * @mbggenerated Tue May 22 12:44:23 GMT+08:00 2018
     */
    int insertSelective(DanmuZan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu_zan
     *
     * @mbggenerated Tue May 22 12:44:23 GMT+08:00 2018
     */
    List<DanmuZan> selectByExample(DanmuZanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu_zan
     *
     * @mbggenerated Tue May 22 12:44:23 GMT+08:00 2018
     */
    DanmuZan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu_zan
     *
     * @mbggenerated Tue May 22 12:44:23 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") DanmuZan record, @Param("example") DanmuZanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu_zan
     *
     * @mbggenerated Tue May 22 12:44:23 GMT+08:00 2018
     */
    int updateByExample(@Param("record") DanmuZan record, @Param("example") DanmuZanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu_zan
     *
     * @mbggenerated Tue May 22 12:44:23 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(DanmuZan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu_zan
     *
     * @mbggenerated Tue May 22 12:44:23 GMT+08:00 2018
     */
    int updateByPrimaryKey(DanmuZan record);
}