package runtheworld.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import runtheworld.entity.Danmu;
import runtheworld.entity.DanmuExample;

public interface DanmuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Mon May 07 20:40:13 GMT+08:00 2018
     */
    int countByExample(DanmuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Mon May 07 20:40:13 GMT+08:00 2018
     */
    int deleteByExample(DanmuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Mon May 07 20:40:13 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Mon May 07 20:40:13 GMT+08:00 2018
     */
    int insert(Danmu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Mon May 07 20:40:13 GMT+08:00 2018
     */
    int insertSelective(Danmu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Mon May 07 20:40:13 GMT+08:00 2018
     */
    List<Danmu> selectByExample(DanmuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Mon May 07 20:40:13 GMT+08:00 2018
     */
    Danmu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Mon May 07 20:40:13 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Danmu record, @Param("example") DanmuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Mon May 07 20:40:13 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Danmu record, @Param("example") DanmuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Mon May 07 20:40:13 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Danmu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danmu
     *
     * @mbggenerated Mon May 07 20:40:13 GMT+08:00 2018
     */
    int updateByPrimaryKey(Danmu record);
}